on: push 

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node
      uses: actions/setup-node@v1
      with: 
        node-version: 16

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy
      uses: yang-ju-web/gitee-pages-action@main
      with:
        gitee-repository: lsk_ciao/music-player 
        gitee-branch: main
        folder: dist